import os
import sys

baseName = os.path.basename(__file__)
dirName = os.path.dirname(__file__)

sys.path.append(dirName + r'/../..')

from RFEM.initModel import Model
from RFEM.initModel import saveFile
from RFEM.enums import ActionCategoryType
from RFEM.LoadCasesAndCombinations.designSituation import DesignSituation, DesignSituationType
from RFEM.LoadCasesAndCombinations.loadCase import LoadCase


if __name__ == '__main__':

    Model(True, "Model 1")
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_ACCIDENTAL_SANS)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_1)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_1_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_ACCIDENTAL)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_2)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_2_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_3)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_3_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_4)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_4_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_5)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_5_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_6)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_APPENDIX_C_6_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_A_ACCIDENTAL)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_A)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_B)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_C)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_D)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_E)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_F)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_G)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_A)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_B)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_C)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_D)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_E)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_F)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_5_P_G)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_1)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_1_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_2)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_2_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_3)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_3_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_4)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_4_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_5)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_5_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_6)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_6_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_7)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CHAPTER_9_7_08)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CLAUSE_7_2_2)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CLAUSE_7_2_6_A)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CLAUSE_7_2_6_B)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_CLAUSE_7_2_6_C)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EARTHQUAKE_LIMIT_STATE_AISC341_ASD)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EARTHQUAKE_LIMIT_STATE_AISC341_ASD_OVERSTRENGTH)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EARTHQUAKE_LIMIT_STATE_AISC341_LRFD)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EARTHQUAKE_LIMIT_STATE_AISC341_LRFD_OVERSTRENGTH)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EARTHQUAKE_LIMIT_STATE_CSA_S16)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EFFECTIVE_SEISMIC_WEIGHT)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EQUILIBRIUM_ACCIDENTAL)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EQUILIBRIUM_FUNDAMENTAL)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EQUILIBRIUM_SEISMIC)
    #DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_FIRE)
    DesignSituation(1, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_PSI_1_1)
    DesignSituation(2, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_PSI_2_1)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_SNOW_PSI_1_1)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_SNOW_PSI_2_1)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_ACCIDENTAL_TWO_STARS)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_EXCEPTIONAL_SNOW)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_LOAD_CASE_1)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_LOAD_CASE_2)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_LOAD_CASE_3)
    #DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_LOAD_CASE_4)
    DesignSituation(3, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_PERMANENT_AND_TRANSIENT)
    #DesignSituation(4, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_PERMANENT_FUNDAMENTAL)
    #DesignSituation(4, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_PERMANENT_TRANSIENT_BEARINGS_EXCHANGE)
    DesignSituation(4, DesignSituationType.DESIGN_SITUATION_TYPE_EQU_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_E_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FAILURE_OF_STRUCTURE_ACCIDENTAL)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FAILURE_OF_STRUCTURE_FUNDAMENTAL)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FAILURE_OF_STRUCTURE_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FATIGUE)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FIRE_LIMIT_STATE_AISC360)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FIRE_LIMIT_STATE_NDS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FUNDAMENTAL_PERMANENT)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_FUNDAMENTAL_VARIABLE)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_1_ACCIDENTAL_PSI_1_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_1_ACCIDENTAL_PSI_2_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_1_PERMANENT_AND_TRANSIENT_6_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_1_PERMANENT_AND_TRANSIENT_6_10A_AND_6_10B)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_1_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_2_ACCIDENTAL_PSI_1_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_2_ACCIDENTAL_PSI_2_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_2_PERMANENT_AND_TRANSIENT_6_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_2_PERMANENT_AND_TRANSIENT_6_10A_AND_6_10B)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_1_2_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_2_ACCIDENTAL_PSI_1_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_2_ACCIDENTAL_PSI_2_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_2_PERMANENT_AND_TRANSIENT_6_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_2_PERMANENT_AND_TRANSIENT_6_10A_AND_6_10B)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_2_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_3_ACCIDENTAL_PSI_1_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_3_ACCIDENTAL_PSI_2_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_3_PERMANENT_AND_TRANSIENT_6_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_3_PERMANENT_AND_TRANSIENT_6_10A_AND_6_10B)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_3_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_ACCIDENTAL_PSI_1_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_ACCIDENTAL_PSI_2_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_PERMANENT_AND_TRANSIENT_SANS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_PERMANENT_FUNDAMENTAL)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_PERMANENT_TRANSIENT)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_GEO_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_HYD_ACCIDENTAL_PSI_1_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_HYD_ACCIDENTAL_PSI_2_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_HYD_PERMANENT_AND_TRANSIENT)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_HYD_SEISMIC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_IRREVERSIBLE_SANS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_FIRE)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_CASE)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_CASE_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_CASE_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_CASE_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_LIVE_LOAD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_PERMANENT_LOAD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_SERVICEABILITY_TOTAL_LOAD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_CASE)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_CASE_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_CASE_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_CASE_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_CASE_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_LIMIT_STATE_OF_STRENGTH_CASE_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_REVERSIBLE_SANS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1604_3_SERVICEABILITY)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1604_3_SERVICEABILITY_D_L)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1604_3_SERVICEABILITY_KCR_D_L)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1604_3_SERVICEABILITY_L)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1604_3_SERVICEABILITY_L_OR_LR)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1604_3_SERVICEABILITY_S_W)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_2_LRFD_16_7)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_11)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_12)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_13)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_14)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_15)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_16)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_8)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_1_ASD_16_9)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD_16_17)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD_16_18)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD_16_19)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD_16_20)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD_16_21)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_1605_3_2_ASD_16_22)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_5_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_5_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_7)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_10_7_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_16)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_16_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_16_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_16_6_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_16_7)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_16_7_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_3_LRFD_7_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_5_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_6_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_5_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_6A)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_6B)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_6B_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_7)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_8)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_10_8_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_10_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_5)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_6)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_8)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_8_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_9)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_7_16_9_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_8)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_4_ASD_8_OVERSTRENGTH)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_5_EXTRAORDINARY_7_10)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_5_EXTRAORDINARY_7_10_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_5_EXTRAORDINARY_7_10_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_1_STR_INT_7_16)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_1_STR_INT_7_16_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_1_STR_INT_7_16_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_2_STR_INT_7_16)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_2_STR_INT_7_16_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_2_STR_INT_7_16_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SECTION_2_6_2_STR_INT_7_16_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SEIO_SEISMIC_DESIGN_OVERSTRENGTH_LRFD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SEISMIC_MASS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SEISMIC_MASS_NTC)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SEISMIC_WEIGHT_IS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SEI_SEISMIC_DESIGN_LRFD)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATES)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATES_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATES_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATES_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATES_VIBRATION)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_1)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_2)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_3)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_4)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_ADM)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_AISC360)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_LONG_TERM_EFFECT)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_NDS)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SERVICEABILITY_LIMIT_STATE_SHORT_TERM_EFFECT)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SER_SERVICEABILITY_DESIGN)
    #DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_ALL_VARIABLE_ACTIONS_STORAGE)
    DesignSituation(5, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_1)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_2)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_BEARINGS_EXCHANGE)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_COMFORT)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_GB_50011)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_INTEGRITY)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_NTC)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_QUASI_PERMANENT)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_WITH_DIRECT_LOAD)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CHARACTERISTIC_WITH_IMPOSED_DEFORMATION)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_CSA_A23_3)
    #DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_EARTHQUAKE)
    DesignSituation(6, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_FREQUENT)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_FREQUENT_FUNCTIONALITY_COMFORT)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_FREQUENT_NTC)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_G_NZS)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_G_PSI_L_Q_NZS)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_G_PSI_S_Q_NZS)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_G_PSI_S_Q_OR_W_S_NZS)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_NON_FREQUENT)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_ONE_VARIABLE_ACTION_STORAGE)
    #DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_PERMANENT_AND_VARIABLE_GB50)
    DesignSituation(7, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_QUASI_PERMANENT)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_QUASI_PERMANENT_1)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_QUASI_PERMANENT_2)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_QUASI_PERMANENT_NTC)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_RARE)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_SCAFFOLDING)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_SERVICEABILITY_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_SNIP)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_SP63_13330)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_SP63_13330_LONG_TERM_EFFECT)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_SP63_13330_SHORT_TERM_EFFECT)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_VARIABLE_GB50)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_VIBRATION)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_W_S_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_SLS_W_S_OR_E_S_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STABILITY_II_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STABILITY_IV_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STABILITY_I_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STABILITY_VI_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STABILITY_V_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_AND_STABILITY)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_AND_STABILITY_1)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_AND_STABILITY_2)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_AND_STABILITY_3)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_AND_STABILITY_4)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_AND_STABILITY_LIMIT_STATES)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_A_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_B_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_C_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_D_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_E_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_F_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_G_NZS)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_LIMIT_STATE_ADM_ASD)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_LIMIT_STATE_ADM_LRFD)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_LIMIT_STATE_AISC360_ASD)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_LIMIT_STATE_AISC360_LRFD)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_LIMIT_STATE_NDS_ASD)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STRENGTH_LIMIT_STATE_NDS_LRFD)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STR_ACCIDENTAL_FIRE)
    #DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STR_ACCIDENTAL_ONE_STAR)
    DesignSituation(8, DesignSituationType.DESIGN_SITUATION_TYPE_STR_ACCIDENTAL_PSI_1_1)
    DesignSituation(9, DesignSituationType.DESIGN_SITUATION_TYPE_STR_ACCIDENTAL_PSI_2_1)
    #DesignSituation(10, DesignSituationType.DESIGN_SITUATION_TYPE_STR_ACCIDENTAL_SNOW_PSI_1_1)
    #DesignSituation(10, DesignSituationType.DESIGN_SITUATION_TYPE_STR_ACCIDENTAL_SNOW_PSI_2_1)
    #DesignSituation(10, DesignSituationType.DESIGN_SITUATION_TYPE_STR_EXCEPTIONAL_SNOW)
    DesignSituation(10, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_6_10)
    #DesignSituation(11, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_6_10AMOD_6_10B)
    DesignSituation(11, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_6_10A_6_10B)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_6_10_G_1)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_6_10_G_2)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_6_10_G_3)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_AND_TRANSIENT_SANS)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_FUNDAMENTAL)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_PERMANENT_TRANSIENT_BEARINGS_EXCHANGE)
    #DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_P_PERMANENT_AND_TRANSIENT_SANS)
    DesignSituation(12, DesignSituationType.DESIGN_SITUATION_TYPE_STR_SEISMIC)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_STR_STRENGTH_DESIGN_LRFD)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_1_ACCIDENTAL_PSI_1_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_1_ACCIDENTAL_PSI_2_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_1_FUNDAMENTAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_2_ACCIDENTAL_PSI_1_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_2_ACCIDENTAL_PSI_2_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_2_FUNDAMENTAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_3_ACCIDENTAL_PSI_1_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_3_ACCIDENTAL_PSI_2_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_TYPE_3_FUNDAMENTAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_ACCIDENTAL_GB_50068)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_ACCIDENTAL_STORAGE)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_ALL_VARIABLE_ACTIONS_STORAGE)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_CSA_A23_3)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_EXCEPTIONAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_FUNDAMENTAL_EARTHQUAKE_GB_50011)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_FUNDAMENTAL_GB_50068)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_LOAD_CASE_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_LOAD_CASE_2)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_LOAD_CASE_3)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_LOAD_CASE_4)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_NORMAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_ONE_VARIABLE_ACTION_STORAGE)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_SNIP_BASIC)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_SNIP_SPECIAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_SP63_13330)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_SPECIAL)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_STABILITY_AS_NZS)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_STRENGTH_AS_NZS)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_STRENGTH_FIRE_NZS)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULS_STR_GEO_PERMANENT_AND_TRANSIENT)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULTIMATE_LIMIT_STATE)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULTIMATE_LIMIT_STATE_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULTIMATE_LIMIT_STATE_2)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULTIMATE_LIMIT_STATE_3)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULTIMATE_LIMIT_STATE_4)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_ULTIMATE_LIMIT_STATE_5)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_UPL_ACCIDENTAL_PSI_1_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_UPL_ACCIDENTAL_PSI_2_1)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_UPL_PERMANENT_AND_TRANSIENT)
    #DesignSituation(13, DesignSituationType.DESIGN_SITUATION_TYPE_UPL_SEISMIC)


    LoadCase(1, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACCIDENTAL_ACTIONS_A)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACCIDENTAL_ACTION_A)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACCIDENTAL_LOAD_AL)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTIONS_DUE_TO_CRANES_HORIZONTAL_AND_VERTICAL_Q_CR)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTIONS_DURING_EXECUTION_Q_EX)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTIONS_WITH_LIMITED_MAXIMUM_VALUES_Q_LI)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTION_FROM_SOIL_PERMANENT_EARTH_LOADS_GS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTION_FROM_SOIL_PERMANENT_EARTH_PRESSURE_GS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTION_FROM_SOIL_PERMANENT_WATER_PRESSURE_GS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTION_FROM_SOIL_VARIABLE_EARTH_PRESSURE_GS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ACTION_FROM_SOIL_VARIABLE_WATER_PRESSURE_GS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ASH_LOAD_ON_ROOFINGS_ADJACENT_TO_BLAST_FURNACE_TABLE_5_4_1_2_Q_AS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ASH_LOAD_ON_ROOFINGS_TABLE_5_4_1_1_Q_AS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_ASSEMBLY_HALL_THEATER_CINEMA_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_AUTOMOBILE_PASSAGE_AND_GARAGE_ONE_WAY_SLAB_FLOOR_BUS_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_AUTOMOBILE_PASSAGE_AND_GARAGE_ONE_WAY_SLAB_FLOOR_FIRE_ENGINE_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_AUTOMOBILE_PASSAGE_AND_GARAGE_TWO_WAY_SLAB_FLOOR_FIRE_ENGINE_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_AUTOMOBILE_PASSAGE_AND_GARAGE_TWO_WAY_SLAB_ROOF_BUS_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_BALCONY_OTHER_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_BALCONY_POPULATION_MAY_BE_CONCENTRATED_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_BATHROOM_TOILET_AND_WASHROOM_BUILDINGS_IN_ITEM_NO_1_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_BATHROOM_TOILET_AND_WASHROOM_FOR_OTHER_BUILDINGS_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_CANTEEN_DINING_HALL_ORDINARY_ARCHIVES_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_CLASSROOM_LABORATORY_READING_ROOM_MEETING_ROOM_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_DANCE_HALL_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_DWELLING_HOSTEL_HOTEL_OFFICE_HOSPITAL_WARD_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_GYMNASIUM_ARENA_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_KITCHEN_FOR_DINING_HALL_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_KITCHEN_OTHER_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_LAUNDRY_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_PASSAGE_ENTRANCE_HALL_STAIRCASE_HOSTEL_HOTEL_NURSERY_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_PASSAGE_ENTRANCE_HALL_STAIRCASE_OFFICE_CLASSROOM_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_PASSAGE_ENTRANCE_HALL_STAIRCASE_THICK_STREAM_OF_PEOPLE_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_STAIRS_APARTMENT_HOUSE_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_STAIRS_OTHER_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_STANDS_WITHOUT_FIXED_SEAT_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_STOREHOUSE_FOR_COLLECTING_BOOKS_ARCHIVES_STOREROOMS_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_STORES_AND_SHOPS_EXHIBITION_HALLS_STATION_PORT_AIRPORT_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_VENTILATOR_MOTOR_ROOM_ELEVATOR_MOTOR_ROOM_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CIVIL_BUILDINGS_WAREHOUSE_WITH_A_DENSE_CONCENTRATION_OF_SHELVING_Q_CB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CONCENTRATED_AND_RAILING_LOADS_Q_CO)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CONCRETE_PRESSURE_Q4_2)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CONSTRUCTION_AND_MAINTENANCE_LOADS_AND_HORIZONTAL_LOAD_ON_RAILINGS_ACC_TO_5_5_3_Q_CM)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CONSTRUCTION_LOADS_DUE_TO_WORKING_PERSONNEL_Q_CP)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CONSTRUCTION_OPERATIONS_LOADING_Q2_3)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CRANE_LOADS_LIFTING_HOOK_CRANES_OF_WORKING_GRADE_A8_Q_CR)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CRANE_LOADS_WORKING_GRADES_A1_A3_Q_CR)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CRANE_LOADS_WORKING_GRADES_A4_A5_Q_CR)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CRANE_LOADS_WORKING_GRADES_A6_A7_Q_CR)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_CRANE_LOAD_CL)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEAD_LOAD_D)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEAD_LOAD_DL)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEAD_LOAD_GK)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEAD_LOAD_SOIL_DLS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEAD_LOAD_SOIL_DS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEAD_LOAD_SOIL_GKS)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_DEBRIS_EFFECT_Q6_2)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EARTHQUAKE_LOAD_E)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EARTHQUAKE_LOAD_EL)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EARTHQUAKE_LOAD_HORIZONTAL_EH)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EARTHQUAKE_LOAD_VERTICAL_EV)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EARTH_PRESSURE_FE)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EFFECTS_OF_HORIZONTAL_EARTHQUAKE_FORCES_QE)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EQUIPMENT_CHARGES_OF_CONTAINERS_LIQUID_Q_E3)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EQUIPMENT_CHARGES_OF_CONTAINERS_LOOSE_Q_E4)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EQUIPMENT_FORKLIFTS_AND_ELECTRIC_TRUCKS_Q_E5)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EQUIPMENT_ISOLATION_OF_EQUIPMENT_Q_E2)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EQUIPMENT_PERMANENT_EQUIPMENT_Q_E1)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EQUIPMENT_STORED_MATERIALS_AND_PRODUCTS_Q_M)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ERECTION_LOAD_ER)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_EXCEPTIONAL_EXC)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_FLOOD_LOAD_FA)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_FOUNDATION_SUBSIDENCE_QF)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GENERAL_CONSTRUCTION_ELEMENTS_AND_EQUIPMENT_G_GE)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GENERAL_VARIABLE_ACTIONS_Q_GE)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GEOTECHNICAL_LOADS_PERMANENT_GEP)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GEOTECHNICAL_LOADS_VARIABLE_GEV)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR1A_LM1_PEDESTRIAN_CYCLE_TRACK_GR1A)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR1B_SINGLE_AXLE_GR1B)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR2_HORIZONTAL_FORCES_LM1_GR2)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR3_PEDESTRIAN_LOAD_GR3)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR4_CROWD_LOADING_PEDESTRIAN_LOAD_GR4)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR5_SPECIAL_VEHICLES_LM1_GR5)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GR6_LOADS_FOR_BEARINGS_EXCHANGE_GR6)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_GROUND_WATER_FGW)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_HORIZONTAL_EARTHQUAKE_ACTION_EH)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ICE_ACTION_FICE)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ICE_LOADINGS_Q_I)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ICE_QI)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_ACTION_Q)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_DEFORMATIONS_DUE_TO_PRE_STRESSING_P)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_ACCESSIBLE_FLAT_ROOFS_EXCLUDING_CATEGORIES_A_TO_D_Q_J)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_ACCESSIBLE_FLAT_ROOFS_WITH_OCCUPANCY_A_Q_KA)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_ACCESSIBLE_FLAT_ROOFS_WITH_OCCUPANCY_B_Q_KB)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_ACCESSIBLE_FLAT_ROOFS_WITH_OCCUPANCY_C_Q_KC)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_ACCESSIBLE_FLAT_ROOFS_WITH_OCCUPANCY_D_Q_KD)
    #LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_AREAS_WHERE_PEOPLE_CAN_CONGREGATE_Q_C)
    LoadCase(2, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_A_DOMESTIC_RESIDENTIAL_AREAS_QI_A)
    LoadCase(3, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_B_OFFICE_AREAS_QI_B)
    LoadCase(4, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_C_CONGREGATION_AREAS_QI_C)
    LoadCase(5, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_D_SHOPPING_AREAS_QI_D)
    LoadCase(6, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_E_STORAGE_AREAS_QI_E)
    #LoadCase(7, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_E_TRAFFIC_AREA_VEHICLE_WEIGHT_LESS_OR_EQUAL_TO_30_KN_QI_E)
    #LoadCase(7, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_F_ROOFS_ACCESSIBLE_ONLY_PRIVATELY_QI_F)
    LoadCase(7, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_F_TRAFFIC_AREA_VEHICLE_WEIGHT_LESS_OR_EQUAL_TO_30_KN_QI_F)
    #LoadCase(8, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_G1_ROOFS_SLOPE_LESS_THAN_20_Q_G1)
    #LoadCase(8, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_G2_ROOFS_SLOPE_MORE_THAN_40_Q_G2)
    LoadCase(8, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_G_TRAFFIC_AREA_VEHICLE_WEIGHT_LESS_OR_EQUAL_TO_160_KN_QI_G)
    #LoadCase(9, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_H_INACCESSIBLE_ROOFS_QI_H)
    #LoadCase(9, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_H_ROOFS_ACCESSIBLE_ONLY_FOR_MAINTENANCE_QI_H)
    LoadCase(9, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_H_ROOFS_QI_H)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_I_ROOFS_ACCESSIBLE_QI_I)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_I_ROOFS_HELICOPTER_QI_I)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_J_ROOFS_HELIPORT_EQUIPMENT_QI_J)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_K_FLAT_ROOFS_HELICOPTER_QI_K)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_K_FLAT_ROOFS_OTHER_QI_K)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_CATEGORY_K_ROOFS_FOR_SPECIAL_USES_HELIPORTS_QI_K)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_DOMESTIC_AND_RESIDENTIAL_AREAS_Q_A)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_FORK_LIFTS_Q_FL)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_FROM_CRANES_CLASS_11_12_13_Q_CR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_FROM_CRANES_CLASS_1_7_Q_CR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_FROM_CRANES_CLASS_8_Q_CR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_FROM_CRANES_CLASS_9_10_Q_CR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_FROM_CRANES_SUPPORT_FORCES_Q_CR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_HELICOPTER_LOAD_Q_HC)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_INACCESSIBLE_ROOFS_Q_H)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_INDUSTRIAL_USE_Q_E2)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_LIGHT_INDUSTRIAL_USE_Q_E1)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_LIVE_LOADS_LL)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_PUBLIC_AREAS_NOT_SUSCEPTIBLE_TO_CROWDING_Q_B)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_SHOPPING_AREAS_Q_D)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_STORAGE_AREAS_Q_E3)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_TRAFFIC_AND_PARKING_AREAS_FOR_VEHICLES_25_KN_Q_F)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOADS_TRAFFIC_AND_PARKING_AREAS_FOR_VEHICLES_25_KN_TO_160_KN_Q_G)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IMPOSED_LOAD_Q)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIALIZED_CONSTRUCTION_ELEMENTS_G_IN)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIALIZED_CONSTRUCTION_ELEMENTS_WITH_ADDITION_ON_SITE_G_IS)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_COTTON_MILLING_WORKSHOP_TABLE_D_0_1_4_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_GRAIN_PROCESSING_WORKSHOP_TABLE_D_0_1_6_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_MANUFACTURING_WORKSHOP_TABLE_D_0_1_2_ITEM_NO_1_2_4_6_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_MANUFACTURING_WORKSHOP_TABLE_D_0_1_2_ITEM_NO_3_5_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_MANUFACTURING_WORKSHOP_TABLE_D_0_1_2_ITEM_NO_7_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_METAL_WORKING_WORKSHOP_TABLE_D_0_1_1_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_PREPARATORY_WORKSHOP_FOR_TIRE_PLANT_TABLE_D_0_1_5_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INDUSTRIAL_BUILDINGS_SEMICONDUCTOR_PRODUCTION_WORKSHOP_TABLE_D_0_1_3_Q_IB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_INFLUENCES_RESULTING_FROM_TEMPERATURE_CHANGES_SHRINKAGE_OR_CREEP_ETC_T)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_IN_SITU_CONCRETE_LOADING_ALLOWANCE_Q4_1)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LATERAL_EARTH_PRESSURE_H)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIQUID_PRESSURE_FLP)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOADS_ON_ROOFS_HELICOPTER_ON_THE_ROOF_ACC_TO_5_3_2_Q_LR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOADS_ON_ROOFS_MANNED_ROOF_Q_LR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOADS_ON_ROOFS_ROOF_GARDEN_Q_LR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOADS_ON_ROOFS_ROOF_SPORTS_GROUND_Q_LR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOADS_ON_ROOFS_UNMANNED_ROOF_Q_LR)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOAD_DUE_TO_EARTHQUAKE_E)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOAD_DUE_TO_WIND_W)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOAD_L)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LIVE_LOAD_Q)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_CRANES_GROUP_6K_Q_C4)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_CRANES_GROUP_7K_Q_C3)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_CRANES_GROUP_8K_ELASTIC_Q_C2)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_CRANES_GROUP_8K_RIGID_Q_C1)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_CRANES_IN_GENERAL_Q_C1)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_CRANES_OTHER_GROUPS_Q_C5)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_FROM_VEHICLES_Q_V)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOADS_PRODUCED_BY_FLOWING_WATER_Q6_1)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOAD_ARISING_FROM_EXTRAORDINARY_EVENT_AK)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOAD_DUE_TO_FLUIDS_WITH_WELL_DEFINED_PRESSURES_AND_MAXIMUM_HEIGHTS_F)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOAD_DUE_TO_GROUND_WATER_PRESSURE_HW)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOAD_DUE_TO_LATERAL_EARTH_PRESSURE_GROUND_WATER_PRESSURE_H)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_LOAD_DUE_TO_LATERAL_EARTH_PRESSURE_OR_PRESSURE_OF_BULK_MATERIALS_HEB)
    #LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_MAXIMUM_WIND_Q5_1)
    LoadCase(10, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_NONE_NONE)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_NOTIONAL_HORIZONTAL_FORCES_ACCORDING_TO_BS_5950_NK)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_NOTIONAL_LOAD_FOR_STRUCTURAL_INTEGRITY_N)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_OTHER_ACTIONS_QO)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_OTHER_CONSTRUCTION_LOADS_Q_CO)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_OTHER_IMPOSED_PERMANENT_DEFORMATIONS_FOR_EXAMPLE_SETTLEMENT_G_OT)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_OTHER_LIVE_LOADS_QO)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_OTHER_LOADS_Q9)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_OTHER_TYPES_OF_VARIABLE_LOADS_Q_OT)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_EARTH_PRESSURE_G_E)
    #LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_FROM_CRANES_G_CR)
    LoadCase(11, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_G)
    #LoadCase(12, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_G1)
    #LoadCase(12, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_FACTORED_G_GF)
    #LoadCase(12, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_UN_FACTORED_G_GU)
    LoadCase(12, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_IMPOSED_GQ)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_IMPOSED_NON_STRUCTURAL_G2)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_LOADS_FROM_FLUIDS_G_FL)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_NON_STRUCTURAL_G2)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_SELF_WEIGHT_SELF_WEIGHT_OF_SOIL_G)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_SMALL_FLUCTUATIONS_G_ASTERISK)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_SOIL_GS)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PERMANENT_WATER_PRESSURE_G_W)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PLACEMENT_LOADS_QP)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PREMISES_OF_BUILDINGS_UNIFORM_LOADS_2_KN_M2_AND_MORE_Q_U2)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PREMISES_OF_BUILDINGS_UNIFORM_LOADS_LESS_THAN_2_KN_M2_Q_U1)
    #LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PRESTRESSING_Q8_3)
    LoadCase(13, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_PRESTRESS_P)
    #LoadCase(14, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_RAINWATER_PONDING_FPND)
    #LoadCase(14, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_RAIN_LOAD_QR)
    #LoadCase(14, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_RAIN_LOAD_R)
    #LoadCase(14, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ROOF_LIVE_LOAD_LR)
    #LoadCase(14, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ROOF_LIVE_LOAD_QR)
    LoadCase(14, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SEISMIC_ACTIONS_AE)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SEISMIC_AE)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SEISMIC_EFFECTS_Q7)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_STRAINING_FORCE_PERMANENT_TP)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_STRAINING_FORCE_VARIABLE_TV)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_CONCRETE_1600_KG_M3_AND_LESS_ON_BUILDING_SITE_G_C3)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_CONCRETE_1600_KG_M3_AND_LESS_PREFABRICATED_G_C2)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_CONCRETE_MORE_THAN_1600_KG_M3_STONE_TIMBER_G_C1)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_G)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_OF_METAL_STRUCTURES_G_ME)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_OF_PREFABRICATED_STRUCTURES_G_PR)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_OF_STRUCTURES_BUILT_ON_SITE_G_SI)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_Q1_1)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_SOIL_MODIFIED_G_SM)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_SOIL_NATURAL_G_SN)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_STEEL_CONSTRUCTIONS_G_S1)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SELF_WEIGHT_STEEL_CONSTRUCTIONS_OVER_50_OF_TOTAL_LOAD_G_S2)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SERVICEABILITY_EARTHQUAKE_ACTION_ES)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SERVICEABILITY_WIND_ACTION_WS)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SETTLEMENTS_OF_SUPPORTS_SHRINKAGE_SETT)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SETTLEMENT_Q8_2)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ACTION_FSN)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_AND_ICE_Q2_4)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_AND_RAIN_S)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_1_LESS_OR_EQUAL_TO_SK_LESSER_THAN_2_KN_M2_QS)
    #LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_2_LESS_OR_EQUAL_TO_SK_LESSER_THAN_3_KN_M2_QS)
    LoadCase(15, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_FINLAND_ICELAND_QS)
    LoadCase(16, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_H_GREATER_THAN_1000_M_QS)
    LoadCase(17, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_H_LESS_OR_EQUAL_TO_1000_M_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_OUTDOOR_TERRACES_AND_BALCONIES_SK_GREATER_THAN_2_75_KN_M2_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_OUTDOOR_TERRACES_AND_BALCONIES_SK_LESS_OR_EQUAL_TO_2_75_KN_M2_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_SK_GREATER_OR_EQUAL_TO_3_KN_M2_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_SK_GREATER_THAN_2_75_KN_M2_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_ICE_LOADS_SK_LESS_OR_EQUAL_TO_2_75_KN_M2_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_LOADINGS_Q_S)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_LOAD_S)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_LOAD_ZONE_III_S)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_LOAD_ZONE_II_S)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_LOAD_ZONE_I_S)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SNOW_REGION_SAINT_PIERRE_AND_MIQUELON_QS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SOIL_Q1_2)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SPECIAL_LOADINGS_PS)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_STORAGE_AREAS_Q2_2)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_SUPPORTED_CONSTRUCTION_Q2_1)
    #LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_TEMPERATURE_CLIMATIC_INFLUENCES_Q_T)
    LoadCase(18, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_TEMPERATURE_NON_FIRE_QT)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_TEMPERATURE_Q8_1)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_TEMPERATURE_SHRINKAGE_CREEP_ETC_T)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_THERMAL_ACTIONS_ARISING_FROM_THE_FIRE_T)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_THERMAL_ACTIONS_QT)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_THERMAL_ACTION_ACCORDING_TO_9_1_3_T)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_TORNADO_LOAD_WT)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ULTIMATE_EARTHQUAKE_ACTION_EU)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_ULTIMATE_WIND_ACTION_WU)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_UNEVEN_SETTLEMENTS_G_US)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_UNIT_LOADS_QU)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_FACTORED_GROUNDWATER_GEF1)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_FACTORED_GROUND_WATER_FLUIDS_GEF2)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_FACTORED_OTHER_ACTIONS_GEF3)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_UN_FACTORED_GROUNDWATER_GEU1)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_UN_FACTORED_GROUND_WATER_FLUIDS_GEU2)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_GEOTECHNICAL_ACTIONS_SOIL_PARAMETERS_UN_FACTORED_OTHER_ACTIONS_GEU3)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_LOADS_FROM_FLUIDS_Q_FL)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_PERSISTENT_HORIZONTAL_IMPOSED_ACTIONS_Q3)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VARIABLE_Q)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_VERTICAL_EARTHQUAKE_ACTION_EV)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WEIGHT_OF_ICE_DI)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOADINGS_Q_W)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOADS_FWK_EXECUTION_QWE)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOADS_FWK_PERSISTENT_DESIGN_SITUATIONS_QWP)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOADS_FW_QW)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOAD_ACCORDING_TO_8_1_4_W)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOAD_W)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOAD_WK)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_LOAD_WL)
    #LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_ON_ICE_DETERMINED_IN_ACCORDANCE_WITH_SECTION_10_WI)
    LoadCase(19, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WIND_QW)
    #LoadCase(20, 'Self-Weight', [True, 0.0, 0.0, 1.0], ActionCategoryType.ACTION_CATEGORY_WORKING_WIND_Q5_2)
