# TODO maybe rename this file to "complexTypes.py" as it is reffered to in WSDL
class BaseObject:
    """
    Base class for special objects, each of this object needs to be represented as dict, so it can be used in RFEM API.
    Therefore we need to implement toDict method, so this base class is here to avoid code duplication with the class inheritance.
    Each new object should inherit from this class.
    """
    def toDict(self):
        return self.__dict__

class DxfFileModelObject(BaseObject):
    def __init__(
        self,
        no = None,
        origin_coordinate_x = None,
        origin_coordinate_y = None,
        origin_coordinate_z = None,
        rotation_angles_sequence = {'value': None}, # TODO maybe it is different object
        rotation_angle_1 = None,
        rotation_angle_2 = None,
        rotation_angle_3 = None,
        user_defined_name_enabled = None,
        name = None,
        filename = None,
        coordinate_system = None,
        insert_point = {'value' : None},
        scale_is_nonuniform = None,
        scale_is_defined_as_relative = None,
        scale_relative = None,
        scale_absolute = None,
        scale_relative_x = None,
        scale_relative_y = None,
        scale_relative_z = None,
        scale_absolute_x = None,
        scale_absolute_y = None,
        scale_absolute_z = None
    ):
        self.no = no
        self.origin_coordinate_x = origin_coordinate_x
        self.origin_coordinate_y = origin_coordinate_y
        self.origin_coordinate_z = origin_coordinate_z
        self.rotation_angles_sequence = rotation_angles_sequence
        self.rotation_angle_1 = rotation_angle_1
        self.rotation_angle_2 = rotation_angle_2
        self.rotation_angle_3 = rotation_angle_3
        self.user_defined_name_enabled = user_defined_name_enabled
        self.name = name
        self.filename = filename
        self.coordinate_system = coordinate_system
        self.insert_point = insert_point
        self.scale_is_nonuniform = scale_is_nonuniform
        self.scale_is_defined_as_relative = scale_is_defined_as_relative
        self.scale_relative = scale_relative
        self.scale_absolute = scale_absolute
        self.scale_relative_x = scale_relative_x
        self.scale_relative_y = scale_relative_y
        self.scale_relative_z = scale_relative_z
        self.scale_absolute_x = scale_absolute_x
        self.scale_absolute_y = scale_absolute_y
        self.scale_absolute_z = scale_absolute_z

class BuildingStory(BaseObject):
    def __init__(
        self,
        no = None,
        type = None,
        user_defined_name_enabled = None,
        name = None,
        story_no = None,
        elevation = None,
        bottom_elevation = None,
        height = None,
        modified_height = None,
        thickness = None,
        info = None,
        comment = None,
        total_info = None,
        modify_geometry_type = None,
        thickness_type = None,
        slab_stiffness_type = None,
        create_result_sections = None,
        floor_stiffness_type = None,
        vertical_result_line_active = None,
        vertical_result_line_position_x = None,
        vertical_result_line_position_y = None,
        vertical_result_line_relative = None,
        vertical_result_line_relative_position_x = None,
        vertical_result_line_relative_position_y = None,
        mass = None,
        center_of_gravity_x = None,
        center_of_gravity_y = None,
        id_for_export_import = None,
        metadata_for_export_import = None
    ):

        self.no = no
        self.type = type
        self.user_defined_name_enabled = user_defined_name_enabled
        self.name = name
        self.story_no = story_no
        self.elevation = elevation
        self.bottom_elevation = bottom_elevation
        self.height = height
        self.modified_height = modified_height
        self.thickness = thickness
        self.info = info
        self.comment = comment
        self.total_info = total_info
        self.modify_geometry_type = modify_geometry_type
        self.thickness_type = thickness_type
        self.slab_stiffness_type = slab_stiffness_type
        self.create_result_sections = create_result_sections
        self.floor_stiffness_type = floor_stiffness_type
        self.vertical_result_line_active = vertical_result_line_active
        self.vertical_result_line_position_x = vertical_result_line_position_x
        self.vertical_result_line_position_y = vertical_result_line_position_y
        self.vertical_result_line_relative = vertical_result_line_relative
        self.vertical_result_line_relative_position_x = vertical_result_line_relative_position_x
        self.vertical_result_line_relative_position_y = vertical_result_line_relative_position_y
        self.mass = mass
        self.center_of_gravity_x = center_of_gravity_x
        self.center_of_gravity_y = center_of_gravity_y
        self.id_for_export_import = id_for_export_import
        self.metadata_for_export_import = metadata_for_export_import

class ClippingBox(BaseObject):
    def __init__(
        self,
        no = None,
        user_defined_name_enabled = None,
        name = None,
        coordinate_system = None,
        origin_coordinates = {'value': None}, # TODO not sure if it is correct
        origin_coordinate_x = None,
        origin_coordinate_y = None,
        origin_coordinate_z = None,
        dimensions = {'value': None}, # TODO not sure if it is correct
        dimension_x = None,
        dimension_y = None,
        dimension_z = None,
        comment = None,
        id_for_export_import = None,
        metadata_for_export_import = None
    ):
        self.no = no
        self.user_defined_name_enabled = user_defined_name_enabled
        self.name = name
        self.coordinate_system = coordinate_system
        self.origin_coordinates = origin_coordinates
        self.origin_coordinate_x = origin_coordinate_x
        self.origin_coordinate_y = origin_coordinate_y
        self.origin_coordinate_z = origin_coordinate_z
        self.dimensions = dimensions
        self.dimension_x = dimension_x
        self.dimension_y = dimension_y
        self.dimension_z = dimension_z
        self.comment = comment
        self.id_for_export_import = id_for_export_import
        self.metadata_for_export_import = metadata_for_export_import

class ClippingPlane(BaseObject):
    def __init__(
        self,
        no = None,
        type = None,
        name = None,
        coordinate_system = None,
        invert_clipping_side = None,
        origin_coordinates = {'value': None}, # TODO not sure if it is correct
        origin_coordinate_x = None,
        origin_coordinate_y = None,
        origin_coordinate_z = None,
        u_axis_point_coordinates = {'value': None}, # TODO not sure if it is correct
        u_axis_point_coordinate_x = None,
        u_axis_point_coordinate_y = None,
        u_axis_point_coordinate_z = None,
        clipping_plane_point_coordinates = {'value': None}, # TODO not sure if it is correct
        clipping_plane_point_coordinate_x = None,
        clipping_plane_point_coordinate_y = None,
        clipping_plane_point_coordinate_z = None,
        clipping_plane_angle = None,
        rotation_angles_sequence = {'value': None}, # TODO not sure if it is correct
        rotation_angle_1 = None,
        rotation_angle_2 = None,
        rotation_angle_3 = None,
        orientation = None,
        comment = None,
        is_generated = None,
        generating_object_info = None,
        id_for_export_import = None,
        metadata_for_export_import = None
    ):
        self.no = no
        self.type = type
        self.name = name
        self.coordinate_system = coordinate_system
        self.invert_clipping_side = invert_clipping_side
        self.origin_coordinates = origin_coordinates
        self.origin_coordinate_x = origin_coordinate_x
        self.origin_coordinate_y = origin_coordinate_y
        self.origin_coordinate_z = origin_coordinate_z
        self.u_axis_point_coordinates = u_axis_point_coordinates
        self.u_axis_point_coordinate_x = u_axis_point_coordinate_x
        self.u_axis_point_coordinate_y = u_axis_point_coordinate_y
        self.u_axis_point_coordinate_z = u_axis_point_coordinate_z
        self.clipping_plane_point_coordinates = clipping_plane_point_coordinates
        self.clipping_plane_point_coordinate_x = clipping_plane_point_coordinate_x
        self.clipping_plane_point_coordinate_y = clipping_plane_point_coordinate_y
        self.clipping_plane_point_coordinate_z = clipping_plane_point_coordinate_z
        self.clipping_plane_angle = clipping_plane_angle
        self.rotation_angles_sequence = rotation_angles_sequence
        self.rotation_angle_1 = rotation_angle_1
        self.rotation_angle_2 = rotation_angle_2
        self.rotation_angle_3 = rotation_angle_3
        self.orientation = orientation
        self.comment = comment
        self.is_generated = is_generated
        self.generating_object_info = generating_object_info
        self.id_for_export_import = id_for_export_import
        self.metadata_for_export_import = metadata_for_export_import

class ConstructionStage(BaseObject):
    def __init__(
        self,
        no = None,
        user_defined_name_enabled = None,
        name = None,
        to_solve = None,
        continue_on_construction_stage = None,
        start_time = None,
        start_date = None,
        end_time = None,
        end_date = None,
        duration = None,
        loading = None,
        generate_combinations = None,
        static_analysis_settings = None,
        consider_imperfection = None,
        imperfection_case = None,
        structure_modification_enabled = None,
        structure_modification = None,
        stability_analysis_enabled = None,
        stability_analysis = None,
        comment = None,
        load_duration = None,
        are_members_enabled_to_modify = None,
        are_all_members_active = None,
        added_members = None,
        deactivated_members = None,
        active_members = None,
        member_property_modifications = None,
        are_surfaces_enabled_to_modify = None,
        are_all_surfaces_active = None,
        added_surfaces = None,
        deactivated_surfaces = None,
        active_surfaces = None,
        surface_property_modifications = None,
        are_solids_enabled_to_modify = None,
        are_all_solids_active = None,
        added_solids = None,
        deactivated_solids = None,
        active_solids = None,
        solid_property_modifications = None,
        are_nodes_enabled_to_modify = None,
        are_surface_contacts_enabled_to_modify = None,
        are_all_surface_contacts_active = None,
        added_surface_contacts = None,
        deactivated_surface_contacts = None,
        active_surface_contacts = None,
        are_rigid_links_enabled_to_modify = None,
        are_all_rigid_links_active = None,
        added_rigid_links = None,
        deactivated_rigid_links = None,
        active_rigid_links = None,
        support_all_nodes_with_support = None,
        add_nodes_to_support = None,
        deactivated_nodes_for_support = None,
        currently_supported_nodes = None,
        are_line_supports_enabled_to_modify = None,
        support_all_lines_with_support = None,
        add_lines_to_support = None,
        deactivated_lines_for_support = None,
        currently_supported_lines = None,
        are_line_hinges_enabled_to_modify = None,
        are_all_hinges_assigned = None,
        add_line_hinges = None,
        deactivated_line_hinges = None,
        current_line_hinges = None,
        are_line_welded_joints_enabled_to_modify = None,
        are_all_welds_assigned = None,
        add_line_welded_joints = None,
        deactivated_line_welded_joints = None,
        current_line_welded_joints = None,
        geotechnical_analysis_reset_small_strain_history = None,
        id_for_export_import = None,
        metadata_for_export_import = None
    ):
        self.no = no
        self.user_defined_name_enabled = user_defined_name_enabled
        self.name = name
        self.to_solve = to_solve
        self.continue_on_construction_stage = continue_on_construction_stage
        self.start_time = start_time
        self.start_date = start_date
        self.end_time = end_time
        self.end_date = end_date
        self.duration = duration
        self.loading = loading
        self.generate_combinations = generate_combinations
        self.static_analysis_settings = static_analysis_settings
        self.consider_imperfection = consider_imperfection
        self.imperfection_case = imperfection_case
        self.structure_modification_enabled = structure_modification_enabled
        self.structure_modification = structure_modification
        self.stability_analysis_enabled = stability_analysis_enabled
        self.stability_analysis = stability_analysis
        self.comment = comment
        self.load_duration = load_duration
        self.are_members_enabled_to_modify = are_members_enabled_to_modify
        self.are_all_members_active = are_all_members_active
        self.added_members = added_members
        self.deactivated_members = deactivated_members
        self.active_members = active_members
        self.member_property_modifications = member_property_modifications
        self.are_surfaces_enabled_to_modify = are_surfaces_enabled_to_modify
        self.are_all_surfaces_active = are_all_surfaces_active
        self.added_surfaces = added_surfaces
        self.deactivated_surfaces = deactivated_surfaces
        self.active_surfaces = active_surfaces
        self.surface_property_modifications = surface_property_modifications
        self.are_solids_enabled_to_modify = are_solids_enabled_to_modify
        self.are_all_solids_active = are_all_solids_active
        self.added_solids = added_solids
        self.deactivated_solids = deactivated_solids
        self.active_solids = active_solids
        self.solid_property_modifications = solid_property_modifications
        self.are_nodes_enabled_to_modify = are_nodes_enabled_to_modify
        self.are_surface_contacts_enabled_to_modify = are_surface_contacts_enabled_to_modify
        self.are_all_surface_contacts_active = are_all_surface_contacts_active
        self.added_surface_contacts = added_surface_contacts
        self.deactivated_surface_contacts = deactivated_surface_contacts
        self.active_surface_contacts = active_surface_contacts
        self.are_rigid_links_enabled_to_modify = are_rigid_links_enabled_to_modify
        self.are_all_rigid_links_active = are_all_rigid_links_active
        self.added_rigid_links = added_rigid_links
        self.deactivated_rigid_links = deactivated_rigid_links
        self.active_rigid_links = active_rigid_links
        self.support_all_nodes_with_support = support_all_nodes_with_support
        self.add_nodes_to_support = add_nodes_to_support
        self.deactivated_nodes_for_support = deactivated_nodes_for_support
        self.currently_supported_nodes = currently_supported_nodes
        self.are_line_supports_enabled_to_modify = are_line_supports_enabled_to_modify
        self.support_all_lines_with_support = support_all_lines_with_support
        self.add_lines_to_support = add_lines_to_support
        self.deactivated_lines_for_support = deactivated_lines_for_support
        self.currently_supported_lines = currently_supported_lines
        self.are_line_hinges_enabled_to_modify = are_line_hinges_enabled_to_modify
        self.are_all_hinges_assigned = are_all_hinges_assigned
        self.add_line_hinges = add_line_hinges
        self.deactivated_line_hinges = deactivated_line_hinges
        self.current_line_hinges = current_line_hinges
        self.are_line_welded_joints_enabled_to_modify = are_line_welded_joints_enabled_to_modify
        self.are_all_welds_assigned = are_all_welds_assigned
        self.add_line_welded_joints = add_line_welded_joints
        self.deactivated_line_welded_joints = deactivated_line_welded_joints
        self.current_line_welded_joints = current_line_welded_joints
        self.geotechnical_analysis_reset_small_strain_history = geotechnical_analysis_reset_small_strain_history
        self.id_for_export_import = id_for_export_import
        self.metadata_for_export_import = metadata_for_export_import

class DesignSituation(BaseObject):
    def __init__(
        self,
        no = None,
        user_defined_name_enabled = None,
        name = None,
        design_situation_type = None,
        active = None,
        comment = None,
        is_generated = None,
        generating_object_info = None,
        combination_wizard = None,
        consider_inclusive_exclusive_load_cases = None,
        relationship_between_load_cases = None,
        case_objects = None,
        id_for_export_import = None,
        metadata_for_export_import = None
    ):
        self.no = no
        self.user_defined_name_enabled = user_defined_name_enabled
        self.name = name
        self.design_situation_type = design_situation_type
        self.active = active
        self.comment = comment
        self.is_generated = is_generated
        self.generating_object_info = generating_object_info
        self.combination_wizard = combination_wizard
        self.consider_inclusive_exclusive_load_cases = consider_inclusive_exclusive_load_cases
        self.relationship_between_load_cases = relationship_between_load_cases
        self.case_objects = case_objects
        self.id_for_export_import = id_for_export_import
        self.metadata_for_export_import = metadata_for_export_import

class Dimension(BaseObject):
    def __init__(
        self,
        no = None,
        type = None,
        user_defined_name_enabled = None,
        name = None,
        display_properties_index = None,
        dimension_line_offset = None,
        is_custom_vertical_position = None,
        custom_vertical_position = None,
        is_custom_horizontal_position = None,
        custom_horizontal_position = None,
        symbol = None,
        comment = None,
        measured_length = None,
        measured_lengths = None,
        measured_angle = None,
        measured_angles = None,
        measured_slope = None,
        is_global_dimension_line_offset = None,
        linear_coordinate_system = None,
        linear_reference = None,
        linear_plane = None,
        linear_global_dimension_line_offset = None,
        linear_global_dimension_line_offset_x = None,
        linear_global_dimension_line_offset_y = None,
        linear_global_dimension_line_offset_z = None,
        linear_reference_table = None,
        arc_length_reference_line = None,
        arc_length_reference_table = None,
        arc_length_angle_greater_than_180 = None,
        angular_reference_table = None,
        angular_quadrant = None,
        angular_angle_greater_than_180 = None,
        radius_diameter_reference_line = None,
        radius_diameter_is_target_point = None,
        radius_diameter_target_point_coordinates = None,
        radius_diameter_target_point_coordinate_x = None,
        radius_diameter_target_point_coordinate_y = None,
        radius_diameter_target_point_coordinate_z = None,
        radius_diameter_position_on_line = None,
        slope_coordinate_system = None,
        slope_plane = None,
        slope_reference_line = None,
        slope_direction = None,
        slope_refer_distance_from_line_end = None,
        slope_position_is_relative = None,
        slope_position_absolute = None,
        slope_position_relative = None,
        elevation_reference_object_type = None,
        elevation_reference_surface = None,
        elevation_reference_node = None,
        elevation_reference_control_point = None,
        elevation_reference_point_coordinates = None,
        elevation_reference_point_coordinate_x = None,
        elevation_reference_point_coordinate_y = None,
        elevation_reference_point_coordinate_z = None,
        elevation_distance_from_picked_position = None,
        elevation_rotation_around_z = None,
        elevation_reference_level_height = None,
        elevation_is_altitude = None,
        elevation_altitude = None,
        is_generated = None,
        generating_object_info = None,
        id_for_export_import = None,
        metadata_for_export_import = None
    ):
        self.no = no
        self.type = type
        self.user_defined_name_enabled = user_defined_name_enabled
        self.name = name
        self.display_properties_index = display_properties_index
        self.dimension_line_offset = dimension_line_offset
        self.is_custom_vertical_position = is_custom_vertical_position
        self.custom_vertical_position = custom_vertical_position
        self.is_custom_horizontal_position = is_custom_horizontal_position
        self.custom_horizontal_position = custom_horizontal_position
        self.symbol = symbol
        self.comment = comment
        self.measured_length = measured_length
        self.measured_lengths = measured_lengths
        self.measured_angle = measured_angle
        self.measured_angles = measured_angles
        self.measured_slope = measured_slope
        self.is_global_dimension_line_offset = is_global_dimension_line_offset
        self.linear_coordinate_system = linear_coordinate_system
        self.linear_reference = linear_reference
        self.linear_plane = linear_plane
        self.linear_global_dimension_line_offset = linear_global_dimension_line_offset
        self.linear_global_dimension_line_offset_x = linear_global_dimension_line_offset_x
        self.linear_global_dimension_line_offset_y = linear_global_dimension_line_offset_y
        self.linear_global_dimension_line_offset_z = linear_global_dimension_line_offset_z
        self.linear_reference_table = linear_reference_table
        self.arc_length_reference_line = arc_length_reference_line
        self.arc_length_reference_table = arc_length_reference_table
        self.arc_length_angle_greater_than_180 = arc_length_angle_greater_than_180
        self.angular_reference_table = angular_reference_table
        self.angular_quadrant = angular_quadrant
        self.angular_angle_greater_than_180 = angular_angle_greater_than_180
        self.radius_diameter_reference_line = radius_diameter_reference_line
        self.radius_diameter_is_target_point = radius_diameter_is_target_point
        self.radius_diameter_target_point_coordinates = radius_diameter_target_point_coordinates
        self.radius_diameter_target_point_coordinate_x = radius_diameter_target_point_coordinate_x
        self.radius_diameter_target_point_coordinate_y = radius_diameter_target_point_coordinate_y
        self.radius_diameter_target_point_coordinate_z = radius_diameter_target_point_coordinate_z
        self.radius_diameter_position_on_line = radius_diameter_position_on_line
        self.slope_coordinate_system = slope_coordinate_system
        self.slope_plane = slope_plane
        self.slope_reference_line = slope_reference_line
        self.slope_direction = slope_direction
        self.slope_refer_distance_from_line_end = slope_refer_distance_from_line_end
        self.slope_position_is_relative = slope_position_is_relative
        self.slope_position_absolute = slope_position_absolute
        self.slope_position_relative = slope_position_relative
        self.elevation_reference_object_type = elevation_reference_object_type
        self.elevation_reference_surface = elevation_reference_surface
        self.elevation_reference_node = elevation_reference_node
        self.elevation_reference_control_point = elevation_reference_control_point
        self.elevation_reference_point_coordinates = elevation_reference_point_coordinates
        self.elevation_reference_point_coordinate_x = elevation_reference_point_coordinate_x
        self.elevation_reference_point_coordinate_y = elevation_reference_point_coordinate_y
        self.elevation_reference_point_coordinate_z = elevation_reference_point_coordinate_z
        self.elevation_distance_from_picked_position = elevation_distance_from_picked_position
        self.elevation_rotation_around_z = elevation_rotation_around_z
        self.elevation_reference_level_height = elevation_reference_level_height
        self.elevation_is_altitude = elevation_is_altitude
        self.elevation_altitude = elevation_altitude
        self.is_generated = is_generated
        self.generating_object_info = generating_object_info
        self.id_for_export_import = id_for_export_import
        self.metadata_for_export_import = metadata_for_export_import